-- MySQL Script generated by MySQL Workbench
-- Sun 06 Jun 2021 21:10:08 CAT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema zamtel_assessment
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zamtel_assessment
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zamtel_assessment` ;
USE `zamtel_assessment` ;

-- -----------------------------------------------------
-- Table `zamtel_assessment`.`CustomerProfile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zamtel_assessment`.`CustomerProfile` (
  `customerProfileID` INT NOT NULL AUTO_INCREMENT,
  `fName` VARCHAR(45) NOT NULL,
  `lName` VARCHAR(45) NOT NULL,
  `otherNames` VARCHAR(100) NOT NULL,
  `dateOfBirth` DATE NOT NULL,
  `idNumber` VARCHAR(45) NOT NULL,
  `gender` ENUM('Male', 'Female') NOT NULL,
  `customerType` VARCHAR(45) NOT NULL,
  `customerProfileStatusCode` VARCHAR(45) NOT NULL,
  `occupation` VARCHAR(100) NOT NULL,
  `village` VARCHAR(100) NOT NULL,
  `chiefdom` VARCHAR(100) NOT NULL,
  `longitude` VARCHAR(100) NOT NULL,
  `latitude` VARCHAR(100) NOT NULL,
  `country` VARCHAR(100) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`customerProfileID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zamtel_assessment`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zamtel_assessment`.`Address` (
  `addressID` INT NOT NULL,
  `plotNumber` VARCHAR(45) NOT NULL,
  `streetName` VARCHAR(100) NOT NULL,
  `area` VARCHAR(100) NOT NULL,
  `province` VARCHAR(45) NOT NULL,
  `town` VARCHAR(45) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `customerProfileID` INT NOT NULL,
  PRIMARY KEY (`addressID`),
  CONSTRAINT `fk_Address_1`
    FOREIGN KEY (`customerProfileID`)
    REFERENCES `zamtel_assessment`.`CustomerProfile` (`customerProfileID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zamtel_assessment`.`ExtendedAddress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zamtel_assessment`.`ExtendedAddress` (
  `extendedAddressID` INT NOT NULL,
  `landMark` VARCHAR(100) NOT NULL,
  `road` VARCHAR(100) NOT NULL,
  `neighborhood` VARCHAR(100) NOT NULL,
  `sectionName` VARCHAR(100) NOT NULL,
  `unitNumber` VARCHAR(45) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `addressID` INT NOT NULL,
  PRIMARY KEY (`extendedAddressID`),
  CONSTRAINT `fk_ExtendedAddress_1`
    FOREIGN KEY (`addressID`)
    REFERENCES `zamtel_assessment`.`Address` (`addressID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zamtel_assessment`.`NextOfKin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zamtel_assessment`.`NextOfKin` (
  `nextOfKinID` INT NOT NULL,
  `fName` VARCHAR(45) NOT NULL,
  `lName` VARCHAR(45) NOT NULL,
  `contactType` VARCHAR(45) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `customerProfileID` INT NOT NULL,
  PRIMARY KEY (`nextOfKinID`),
  CONSTRAINT `fk_NextOfKin_1`
    FOREIGN KEY (`customerProfileID`)
    REFERENCES `zamtel_assessment`.`CustomerProfile` (`customerProfileID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zamtel_assessment`.`SimCard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zamtel_assessment`.`SimCard` (
  `simCardID` INT NOT NULL AUTO_INCREMENT,
  `msisdn` VARCHAR(100) NOT NULL,
  `imei` VARCHAR(100) NOT NULL,
  `serialNumber` VARCHAR(45) NOT NULL,
  `puk` VARCHAR(10) NOT NULL,
  `pin` VARCHAR(10) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `simCardType` VARCHAR(45) NOT NULL,
  `simCardStatus` VARCHAR(45) NOT NULL,
  `customerProfileID` INT NOT NULL,
  PRIMARY KEY (`simCardID`),
  CONSTRAINT `fk_SimCard_1`
    FOREIGN KEY (`customerProfileID`)
    REFERENCES `zamtel_assessment`.`CustomerProfile` (`customerProfileID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
